[tools]
fzf = "latest"
go = "latest"
gradle = "latest"
java = "latest"
jq = "latest"
k3d = "latest"
kubectl = "latest"
kubectx = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "0.11.4"
node = "latest"
opentofu = "latest"
python = "latest"
ruff = "latest"
rust = "latest"
starship = "latest"
terragrunt = "latest"
usage = "latest"
zig = "latest"
