
# Set bind key to reload configuration file
bind r source-file ~/.config/tmux/tmux.conf \; display ​"Reloaded!"

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# Status
set -g status-interval 1
set -g escape-time 2
set -g repeat-time 350
set -g display-time 1500

# Terminal colors
set -g default-terminal "tmux-256color"

# set image support
set -gq allow-passthrough all
set -g visual-activity off

# set terminal title
set -g set-titles on
set -g set-titles-string "#S"

# Enable clipboard
set -g set-clipboard on

# Enable gapeless window
set -g renumber-windows on

# Make index start from 1
set -g base-index 1
setw -g pane-base-index 1

# Set scrollback size
set -g history-limit 9000

# set foncus events on for nvim
set -g focus-events on

# Do not detach when destroying a session
set -g detach-on-destroy off

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# set vi mode globaly
setw -g mode-keys vi

# Set Leader
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set Leader
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane Split Additional Binds
bind \\ split-window -h
bind - split-window -v

# Bar Config
set -g status-style bg=default
