[tools]
fzf = "latest"
go = "latest"
jq = "latest"
yq = "latest"
k3d = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubectx = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
operator-sdk = "latest"
usql = "latest"
zig = "latest"
